# Generated by Django 5.2.5 on 2025-08-30 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
